### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined using last version of log4js (6.4.4) with angular in ssr mode

### ISSUE THREAD

**Issue by myuniverse8** [log4js-node/log4js-node#1225]
Hello,

I am facing one issue in chain of packages: "log4js" -> "streamroller" -> "fs-extra" -> "graceful-fs" and "universalify" 

This is the way how it could be reproduced:
1. Create a new angular project
2. Implement ssr (https://angular.io/guide/universal)
3. Install "log4js" and use it to log something in server.ts file for example:

![image](https://user-images.githubusercontent.com/26976841/161244695-38425ba5-9cda-484d-8e1e-c9889d073a03.png)

5. Build and run this project in ssr mode.

The error will be in terminal:
![image](https://user-images.githubusercontent.com/26976841/161244856-1919a658-0aed-476b-8048-f5ae463ac2eb.png)

After some investigations I have found that in last versions of "log4js" the version of "streamroller" was changed from "2.x.x" to "3.x.x" which caused changing the version of "fs-extra" to the last one.

The issue occurs in "universalify" package which is used by "fs-extra":
![image](https://user-images.githubusercontent.com/26976841/161245477-9307fabf-4e57-4364-9b40-a0bdb7c51738.png)

If we go step up in the callstack then we see this part of code in "fs-extra":
![image](https://user-images.githubusercontent.com/26976841/161245651-ef58cbd9-8f80-4a5b-bd05-36ac878f9c3f.png)

Previously it has a verification that prevented this issue:
![image](https://user-images.githubusercontent.com/26976841/161245749-df8fd336-8b7f-40ed-88f4-7e00c29a3f12.png)

But it was changed in this commit https://github.com/jprichardson/node-fs-extra/commit/f4a880d29c3a699c0695755fe8533d786c55f65f: 

In this case maybe "graceful-fs" should be updated in order to return proper value in this case, because it doesn't return proper value for fs.realpath.native:
![image](https://user-images.githubusercontent.com/26976841/161246376-85ceb6d7-e95d-47f5-9d56-853aa352be94.png)

With "log4js" version 6.3.0 there is no such issue because it uses the old version of "streamroller" which uses the old version of "fs-extra" which has versification mentioned above.

I am not sure on which package I should report this issue but I see it because I am using "log4js" so maybe this is the right place to start. 
 
Could you please check it? 

Thank you very much for your help in advance.

Best Regards,
Andrei

**Comment by myuniverse8** [comment]
Angular: 12.2.16
Angular CLI: 12.2.16
Node: 14.18.1
Package Manager: npm 6.14.15

**Comment by peteriman** [comment]
Seems similar to https://github.com/log4js-node/log4js-node/issues/1186#issuecomment-1033626591.

The verification by `fs-extra` was removed to do away with the redundant checks, assuming most uses NodeJS 9.2.0 onwards.
_(src: https://github.com/jprichardson/node-fs-extra/pull/887)_

NodeJS 14.18.1 should have `fs.realpath.native` as it was implemented since NodeJS 9.2.0.

It does seem like `graceful-fs` wasn't able to load `fs.realpath.native` at all. It should load and provide the native `fs.realpath.native` from NodeJS. 

Are you able to do a `console.log(fs.realpath.native)` before importing of `log4js`? As early as possible, to prevent other dependencies from indirectly altering `fs`, to verify that your NodeJS comes with `fs.realpath.native`.

**Comment by peteriman** [comment]
@myuniverse8, I'm not sure how we can move ahead.
Perhaps would you mind filing an issue with [fs-extra](https://github.com/jprichardson/node-fs-extra) )with the findings we have here_ so that they are considered re-adding the checks or something?

Otherwise, it does seem like [zone.js/node](https://www.npmjs.com/package/zone.js?activeTab=readme) did not factor in `fs` third-level functions. From the [fs API documentation](https://nodejs.org/docs/latest-v14.x/api/fs.html), most are second-level functions (i.e. `fs.XXX`). But there are a 2 exceptions that are in third-level, which are `fs.realpath.native` and `fs.realpathSync.native`.

**Comment by peteriman** [comment]
I have filed an the following issues/PRs on @myuniverse8's behalf in both [zone.js/node](https://github.com/angular/angular/) and [fs-extra](https://github.com/jprichardson/node-fs-extra).
* https://github.com/angular/angular/issues/45546
* https://github.com/jprichardson/node-fs-extra/pull/953

**Comment by myuniverse8** [comment]
Hi, @peteriman, thank you very much for your investigation and your help! I will check both issues/PR.

**Comment by zhaosheng808** [comment]
I have the same problem in Node v8.11.3, 
but it works well in Node v12.13.1;
What do I need to do to make it work well without upgrading Node version?
```
Node: 8.11.3
Log4js: 6.4.4
```

**Comment by zhaosheng808** [comment]
Hi, @peteriman , I've  upgraded NodeJS to v12. Now it can be used normally. thank you very much~

**Comment by peteriman** [comment]
@zhaosheng808, you are welcomed. 
Your case (different from @myuniverse8) is pretty straightforward.

**Comment by peteriman** [comment]
Instead of waiting for the next release `fs-extra`, I took the liberty to defensively patch it in `streamroller`.
Once `fs-extra` has released the fixes, I will upgrade it and revert the defensive patch in `streamroller`.

Fixed in `streamroller@3.0.7` - [changelog](https://github.com/log4js-node/streamroller/blob/master/CHANGELOG.md).
Fixed in `log4js@6.4.5` (which has dependency bumped to `streamroller@3.0.7`).

@myuniverse8 Please try it out and get back to me. Thanks!

**Comment by myuniverse8** [comment]
@peteriman it works for me now. Thank you and your colleagues very much for your support and the quick fix!

**Comment by peteriman** [comment]
Just an update, `fs-extra` has released `10.1.0` ([changelog](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md)) with the patch https://github.com/jprichardson/node-fs-extra/pull/953.

In the next version of `streamroller`, the interim defensive patch will be removed and `fs-extra` upgraded.

**Comment by peteriman** [comment]
Reverted the interim patch in `streamroller@3.0.7` as it has been patched in `fs-extra@10.1.0`.

Released `streamroller@3.0.8` with upgraded `fs-extra@10.1.0` - [changelog](https://github.com/log4js-node/streamroller/blob/master/CHANGELOG.md).
Released `log4js@6.4.6` (which has dependency bumped to `streamroller@3.0.8`).
