### ISSUE TITLE
numBackups documentation not correct

### ISSUE THREAD

**Issue by jkopczyn** [log4js-node/log4js-node#1239]
The switch from `daysToKeep` to `numBackups` in #1149 left the documentation out of date, see [here](https://github.com/log4js-node/log4js-node/blob/110a008ae64b17bf5500e5721517d60835de4d31/docs/dateFile.md?plain=1#L20) and [here](https://github.com/log4js-node/log4js-node/blob/110a008ae64b17bf5500e5721517d60835de4d31/types/log4js.d.ts#L191). It is not clear what the behavior is, or is supposed to be.

**Comment by peteriman** [comment]
The documentation is correct.
https://github.com/log4js-node/log4js-node/blob/110a008ae64b17bf5500e5721517d60835de4d31/docs/dateFile.md?plain=1#L20

The comment in the typescript definition is outdated.
https://github.com/log4js-node/log4js-node/blob/110a008ae64b17bf5500e5721517d60835de4d31/types/log4js.d.ts#L191

**Comment by peteriman** [comment]
The documentation is correct.
https://github.com/log4js-node/log4js-node/blob/110a008ae64b17bf5500e5721517d60835de4d31/docs/dateFile.md?plain=1#L20

---

The comment in the typescript definition is outdated. The update to the documentation in #1181 missed this out.
https://github.com/log4js-node/log4js-node/blob/110a008ae64b17bf5500e5721517d60835de4d31/types/log4js.d.ts#L191

**Comment by peteriman** [comment]
Might have a few other updates to documentation that is not reflected in the comments in the typescript definition.
I shall indicate PR #1240 as draft till I sieve them out.

**Comment by peteriman** [comment]
@jkopczyn For clarity, `daysToKeep` was renamed to `numBackups`.
`numBackups` is the number of old backups (excluding the hot file). 

The variable name `daysToKeep` didn't make sense due to some of the examples below (which are not in days):

- `pattern='yyyy-MM-dd'` and `numBackups=5`:
   1 hot/current + 5 backup(s) of previous days = **6** file(s)
  
- `pattern=yyyy-MM'` and `numBackups=0`:
  1 hot/current + 0 backup(s) of previous months = **1** file(s)
  
- `pattern='yyyy-MM-dd-hh:mm:ss'` and `numBackups=30`:
   1 hot/current + 30 backup(s) of previous seconds = **31** file(s)

**Comment by peteriman** [comment]
Fixed in `log4js@6.4.7`.
