### ISSUE TITLE
[FEATURE] Add `logger.time(<name>)` similar to `console.time(<name>)`

### ISSUE THREAD

**Issue by Creative-Difficulty** [log4js-node/log4js-node#1290]
If I use `console.time()` it gets printed using `console.log`. To have a universal format in my logfiles, I want to print it using `logger.time()` or similar. Is there something like this already? Can I pipe `console.time()` to `logger.<loglevel>()` ?

Help is appreciated!
Greetings,
Alex

**Comment by lamweili** [comment]
I don't think `console.time()` actually does anything by itself?

```js
console.time();
> undefined
```

It does start a timer. Certainly, it does not print out a universal format for the current time.

**Comment by Creative-Difficulty** [comment]
> I don't think `console.time()` actually prints anything by itself?
> 
> ```js
> console.time();
> > undefined
> ```
> 
> I'm guessing you are confused here. Correct me if I'm wrong. It does start a timer. Yet certainly, it does not print out a universal format for the current time.
> 
> You would be better off doing `logger.info(new Date());`

If you want a full explanation of this concept, please visit the NodeJS docs: https://nodejs.org/api/console.html#consoletimelabel
and
https://nodejs.org/api/console.html#consoletimeendlabel

**Comment by Creative-Difficulty** [comment]
No, I am not confused. You certainly are! I never said it prints out "a universal format for the current time".
Further, this is not a question but a feature request!

**Comment by lamweili** [comment]
> No, I am not confused. You certainly are! I never said it prints out "a universal format for the current time". Further, this is not a question but a feature request! Why would you close the issue? Its not completed, resolved or answered in any way!!

---

> If I use `console.time()` it gets printed using `console.log`.

I'm pretty sure you are describing the current behaviour. 
You said that prints when it doesn't. In fact, only `console.timeEnd()` prints.

---

> To have a universal format in my logfiles, I want to print it using `logger.time()` or similar.

You said to have a universal format in your logfiles. I would think the date-time format is the format you are referring to.
I don't consider `default: 751.248ms` or `default: 751.248ms` to be a format. I would consider that as an output.

---

> If you want a full explanation of this concept, please visit the NodeJS docs: https://nodejs.org/api/console.html#consoletimelabel and https://nodejs.org/api/console.html#consoletimeendlabel

I understand the concept, which is why in my reply, I explicitly described that `console.time()` starts a timer and nothing more.
Perhaps I should be even more stringent in my phrasing.

```diff
It does start a timer. Yet certainly, it does not print out a universal format for the current time.
It does start a timer. Yet certainly, it does not print out a universal format for the current time, or even prints out anything at all.
```

**Comment by lamweili** [comment]
> No, I am not confused. You certainly are! I never said it prints out "a universal format for the current time". Further, this is not a question but a feature request! Why would you close the issue? Its not completed, resolved or answered in any way!!

Please refer to the following points which is why I came to that conclusion.

---

1. > If I use `console.time()` it gets printed using `console.log`.

I'm pretty sure you are describing the current behaviour. 
You said that `console.time()` prints when it doesn't. In fact, only `console.timeEnd()` prints.

---

2. > To have a universal format in my logfiles, I want to print it using `logger.time()` or similar.

You said to have a universal format in your logfiles. I would think the date-time format is the format you are referring to.
I don't consider `default: 751.248ms` or `default: 751.248ms` to be a format. I would consider that as an output.

---

3. > If you want a full explanation of this concept, please visit the NodeJS docs: https://nodejs.org/api/console.html#consoletimelabel and https://nodejs.org/api/console.html#consoletimeendlabel

I understand the concept, which is why in my reply, I explicitly described that `console.time()` starts a timer and nothing more.
Perhaps I should be even more stringent in my phrasing.

```diff
- It does start a timer. Yet certainly, it does not print out a universal format for the current time.
+ It does start a timer. Yet certainly, it does not print out a universal format for the current time, or even prints out anything at all.
```

---

4. > Why would you close the issue? Its not completed, resolved or answered in any way!!

In my personal opinion, this feature should not be within the scope of a logging library. It bloats.
As far as I remember, Java's equivalent [`log4j`](https://logging.apache.org/log4j/2.x/manual/usage.html) doesn't have this feature.

It would be better off self-managed:

```js
const timeMap = {};
const time = function(label = "default") {
  if (timeMap[label]) { 
    return `Label '${label}' already exists`; // or other error handling
  } else {
    timeMap[label] = Date.now();
  }
};
const timeEnd = function(label = "default") {
  if (timeMap[label]) {
    return `No such label '${label}'`; // or other error handling
  } else {
    let result = Date.now() - timeMap[label]; // and do formatting
    delete timeMap[label];
    return result;
  }
};
```

And when you want to use it:
```js
logger.info(timeEnd());
```

**Comment by lamweili** [comment]
> No, I am not confused. You certainly are! I never said it prints out "a universal format for the current time". Further, this is not a question but a feature request! Why would you close the issue? Its not completed, resolved or answered in any way!!

Please refer to the following points which is why I came to that conclusion.

---

1. > If I use `console.time()` it gets printed using `console.log`.

I'm pretty sure you are describing the current behaviour. 
You said that `console.time()` prints when it doesn't. In fact, only `console.timeEnd()` prints.

---

2. > To have a universal format in my logfiles, I want to print it using `logger.time()` or similar.

You said to have a universal format in your logfiles. I would think the date-time format is the format you are referring to.
I don't consider `default: 751.248ms` or `default: 751.248ms` to be a format. I would consider that as an output.

---

3. > If you want a full explanation of this concept, please visit the NodeJS docs: https://nodejs.org/api/console.html#consoletimelabel and https://nodejs.org/api/console.html#consoletimeendlabel

I understand the concept, which is why in my reply, I explicitly described that `console.time()` starts a timer and nothing more.
Perhaps I should be even more stringent in my phrasing.

```diff
- It does start a timer. Yet certainly, it does not print out a universal format for the current time.
+ It does start a timer. Yet certainly, it does not print out a universal format for the current time, or even prints out anything at all.
```

---

4. > Why would you close the issue? Its not completed, resolved or answered in any way!!

In my personal opinion, this feature should not be within the scope of a logging library. It bloats.
As far as I remember, Java's equivalent [`log4j`](https://logging.apache.org/log4j/2.x/manual/usage.html) doesn't have this feature.

It would be better off self-managed. It's not hard to code.

```js
const timeMap = {};
const time = function(label = "default") {
  if (timeMap[label]) { 
    return `Label '${label}' already exists`; // or other error handling
  } else {
    timeMap[label] = Date.now();
  }
};
const timeEnd = function(label = "default") {
  if (timeMap[label]) {
    return `No such label '${label}'`; // or other error handling
  } else {
    let result = Date.now() - timeMap[label]; // and do formatting
    delete timeMap[label];
    return result;
  }
};
```

And when you want to use it:
```js
logger.info(timeEnd());
```

**Comment by lamweili** [comment]
Related to #337
