### ISSUE TITLE
Can log4js log an array as a table?

### ISSUE THREAD

**Issue by yviansu** [log4js-node/log4js-node#1373]
If there is an array `arr`, `console.table` can be used to print a table.
Does log4js have similar plugins?

**Comment by lamweili** [comment]
Unfortunately no because Node.js requirement for `log4js` is at the moment Node.js 8.
`console.table()` is only available from Node.js 10 onwards.

In addition, based on common logging frameworks, such as `log4j`, there is no such API interface.
Only `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`.

**Comment by lamweili** [comment]
Unfortunately no because Node.js requirement for `log4js` is at the moment Node.js 8.
`console.table()` is only available from Node.js 10 onwards.

In addition, based on common logging frameworks, such as `log4j`, there is no such API interface.
Only `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`. So as a logging framework, we should be platform agnostic.

**Comment by lamweili** [comment]
Unfortunately no because Node.js requirement for `log4js` is at the moment Node.js 8.
`console.table()` is only available from Node.js 10 onwards.
There is also no way to capture the output from `console.table()` and write to a file.

In addition, based on common logging frameworks, such as `log4j`, there is no such API interface.
Only `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`. So as a logging framework, we should be platform agnostic.

**Comment by aellerton** [comment]
I tend to agree.

Although I can think of times it would be useful to log an array as a table, I'm struggling to think of a time that making that part of logging would be genuinely useful in the long-term.

If I have an array (or object) to capture in a log, it would _probably_ be logged for either immediate debugging or for long term processing.

In the first case I can just hack in `console.table(...)` and in the second case I can just use `JSON.stringify(...)`. 

If the log really does need a nice formatted table then the immediate way would be to format it in the client code (or use a library) and then write to the log. Does the job.

If it's truly a common need in your application then writing a custom appender maybe?

It gets tricky trying to think of an API that would have a clear intent but also powerful enough.

For example, if you write `log.info('this is an array:', pets)` then does that _always_ write all array arguments to a table? Or would it have more fine-grained control? Your own formatting function, while not zero effort, may be a pretty good compromise, e.g. `log.info('format as table:', tableify(pets))`

**Comment by yviansu** [comment]
Yeah, maybe I confused the platform features and logging framework features, thanks for your reply!

I will close this issue since I have got the answer.
