### ISSUE TITLE
log4js breaks chaining of <http.ServerResponse> 

### ISSUE THREAD

**Issue by julianbrummer-gip** [log4js-node/log4js-node#1399]
`res.writeHead(...).end(...)` throws 'can not read properties of undefined (reading end)'

writeHead should return `res` as specified in [NodeJs docs](https://nodejs.org/docs/latest/api/http.html#responsewriteheadstatuscode-statusmessage-headers)
```typescript
// connect-logger.js

// proxy for statusCode.
res.writeHead = (code, headers) => {
    res.writeHead = writeHead;
    res.writeHead(code, headers);

    res.__statusCode = code;
    res.__headers = headers || {};
    return res; // <----
};
```

**Comment by lamweili** [comment]
Thanks! Found that `response.writeHead` returning `response` was added in Node.js 10.17.0.

It wasn't returning anything in prior Node.js versions, and this was probably coded before that.
And yes, the unit tests didn't cover it, so it was undetected.  

> ## 2019-10-22, Version 10.17.0 'Dubnium' (LTS), @BethGriggs
> * **http**: makes response.writeHead return the response (Mark S. Everitt) [#25974](https://github.com/nodejs/node/pull/25974)
> * **http2**: makes response.writeHead return the response (Mark S. Everitt) [#25974](https://github.com/nodejs/node/pull/25974)

_(src: https://raw.githubusercontent.com/nodejs/node/main/doc/changelogs/CHANGELOG_V10.md)_

---

Would you mind creating a PR so that you can be attributed? 🤗

**Comment by MamfTheKramf** [comment]
I made a PR https://github.com/log4js-node/log4js-node/pull/1401.

I updated the tests to also test the chaining functionality
