### ISSUE TITLE
Has the attribute 'daysToKeep' been deleted?

### ISSUE THREAD

**Issue by LiChongs123** [log4js-node/log4js-node#1414]
I want to save only 7 days of logs, but the attribute "daysToKeep" is no longer available. What should I do now?

**Comment by lamweili** [comment]
Are you using `dateFile` appender?
https://log4js-node.github.io/log4js-node/dateFile.html

**Comment by LiChongs123** [comment]
yes

app: {
      type: 'dateFile',
      filename: `${logPath}\\log`,
      pattern: 'yyyy-MM-dd.log',
      alwaysIncludePattern: true,
      maxLogSize: 10485760, // 10485760
      numBackups: 7,
      layout: {
        type: 'pattern',
        pattern: '%d{yyyy-MM-dd hh:mm:ss} | %p     | %m'
      }
    },
Has it been changed to the "numBackups" attribute now? If I generate a lot of log files every day, such as more than 10, then my files from the previous few days will be deleted and only the most recent ones will be retained.

**Comment by lamweili** [comment]
> Has it been changed to the "numBackups" attribute now? If I generate a lot of log files every day, such as more than 10, then my files from the previous few days will be deleted and only the most recent ones will be retained.

The rolling is dependent on the pattern:
- `yyyy-MM-dd.log` would be rotating by the day.
- `yyyy-MM-dd-hh.log` would be rolling by the hour.

The original `daysToKeep` doesn't keep by the days. It is a count of the number of files to be kept. This behaviour did not change. 
Thus, the name `daysToKeep` caused confusion and has been renamed to `numBackups` for clarity.



Given your `maxLogSize` at 10mb and pattern rolling at `yyyy-MM-dd`, you **MAY** have more files per day.
Say today you have 95mb of logs for a day, that will be:
- `yyyy-MM-dd.log` (hot file, 5mb)
- `yyyy-MM-dd.log.1` (10mb)
- `yyyy-MM-dd.log.2` (10mb)
- `yyyy-MM-dd.log.3` (10mb)
- `yyyy-MM-dd.log.4` (10mb)
- `yyyy-MM-dd.log.5` (10mb)
- `yyyy-MM-dd.log.6` (10mb)
- `yyyy-MM-dd.log.7` (10mb)
- `yyyy-MM-dd.log.8` (10mb)
- `yyyy-MM-dd.log.9` (10mb)

And because your `numBackups` is 7 (excluding hot file), that would be:

- `yyyy-MM-dd.log` (hot file, 5mb)
- `yyyy-MM-dd.log.1` (10mb)
- `yyyy-MM-dd.log.2` (10mb)
- `yyyy-MM-dd.log.3` (10mb)
- `yyyy-MM-dd.log.4` (10mb)
- `yyyy-MM-dd.log.5` (10mb)
- `yyyy-MM-dd.log.6` (10mb)
- `yyyy-MM-dd.log.7` (10mb)
- ~`yyyy-MM-dd.log.8` (10mb)~
- ~`yyyy-MM-dd.log.9` (10mb)~

**Comment by LiChongs123** [comment]
heap: {
      type: 'file',
      filename: `${logHeapPath}\\log-jsheap`,
      pattern: 'yyyy-MM-dd.log',
      alwaysIncludePattern: true,
      maxLogSize: 10485760, // 10485760 bytes 10M
      numBackups: 7,
      layout: {
        type: 'pattern',
        pattern: '%d | %p     | %m'
      }
    },

**Comment by LiChongs123** [comment]
I understand, that is to say, if you want only the logs generated in the last 7 days that the framework does not provide, you need to write your own code to implement them

**Comment by lamweili** [comment]
`log4js` behaves similar as `log4j` (`uk.org.simonsite.log4j.appender.TimeAndSizeRollingAppender`) and `log4j2`:
> Every day a new log file will be created, the previous day log will be renamed accordingly to DatePattern param, in addition to this MaxFileSize sets file size limit, once it exceeds - a new log file will also be created. In both cases the oldest log will be deleted, if number of files become greater than MaxRollFileCount.

So yes, if you want to keep by last 7 days while having both `pattern` and `numBackups`, you will need to self-implement.

**Comment by LiChongs123** [comment]
Thanks bro

**Comment by lamweili** [comment]
> Thanks bro

Please close the issue if it has been resolved. Thanks!

**Comment by LiChongs123** [comment]
> > Thanks bro
> 
> Please close the issue if it has been resolved. Thanks!

Hi bro. May I ask why you chose to scroll through deleting logs instead of deleting them by day. What purpose is this considered based on? How do I consider this issue from a product perspective?

**Comment by lamweili** [comment]
That is because `pattern` is not restricted to only days. It depends on how you specify the `pattern`.
It could be `yyyy-MM-dd.log` (day), `yyyy-MM.log` (month), `yyyy-MM-dd-hh.log` (hours), etc.

With `maxLogSize`, we don't want a single file to be larger than the `maxLogSize`, to prevent issues with opening the file later.

So when you have a combination of `pattern` and `maxLogSize`, now you have `X` number of files with `Y` size.
Even if you are deleting by day, your storage could still be exhausted, because a single day can have infinite number of `X`.
It could possibly eat up all of your storage space. So there is a `numBackups` to restrict `X`.

**Comment by LiChongs123** [comment]
Thanks bro
