### ISSUE TITLE
Move all appenders into their own projects?

### ISSUE THREAD

**Issue by nomiddlename** [log4js-node/log4js-node#429]
Moving the appenders into their own projects would make it easier to manage the dependencies (no optional dependences then). It would also make it more obvious how to create new appenders if they all follow the same pattern. It brings the risk of breaking an appender by making changes to core log4js, and not then making sure that all appenders still work.

**Comment by nomiddlename** [comment]
Closing this, as I didn't end up doing it, and I still can't decide if it's a good idea.

**Comment by idenisovs** [comment]
Hi! I guess, that from the point of view of project management, it is better to move appenders (at least the complicated ones) to separated projects. 

It is so because at the moment you have the single project for log4js + appenders, so you have all issues and pull requests for each of them in the same place, which gives you a mess (especially in the time progress). 

If them will be separated to their own projects, you will have each of the with it`s own documentation, unit tests, commit history, pull request and issue lists, so it will be easier to trace and manage them. 

From the point of view of developer, it is also may be better to have separated modules. In this case you will be able to take only those appenders, which you really needed, leaving those,, which you don`t want. 

Decomposition rules. :)

**Comment by nomiddlename** [comment]
Re-opening this, because it is something we should do.

**Comment by nomiddlename** [comment]
This is how I propose we should tackle this:

1. Copy all appenders, apart from stdout/stderr, console, file, dateFile to their own projects in the log4js-node group.
1. Rename the copied appenders, so that they have a different value for type to the current appenders. e.g. "loggly" becomes "@log4js-node/loggly"? (not sure about names to use)
1. Add a deprecation message to the original appenders saying that they will be removed in log4js 3.x, and pointing the user to the new appender - could do with some feedback on the best way to do this without annoying people? Include a flag in config to turn off deprecation warnings maybe?
1. Remove the original appenders (and the the optional deps) in v3

I want to keep the file appenders and stdout/console appenders in the core lib, because they're the ones people use the most.

**Comment by ericnewton76** [comment]
As a consumer of log4js this makes a lot of sense for me. 

Btw thanks for the log4js-api concept, that makes my library dependencies a lot simpler

**Comment by nomiddlename** [comment]
Yep, I've included console in the "core" appenders list in the version-3 branch - it's needed for webpack projects, for instance.

**Comment by nomiddlename** [comment]
Fixed in log4js@3.0.0
