### ISSUE TITLE
Move multiFile appender to its own project

### ISSUE THREAD

**Issue by nomiddlename** [log4js-node/log4js-node#598]
Part of #429 

1. Copy current appender to new project in log4js-node org.
1. Change new appender's name so no conflict with current appender.
1. Publish new appender to NPM.
1. Add deprecation message to current appender, pointing user to new appender, but continue to work.

When log4js v3 released:
1. Replace core appender with warning about removed appender, pointing to new one.
1. Remove rest of core appender.

**Comment by cula** [comment]
I've created a new [repo](https://github.com/log4js-node/multiFile). I'll try it.

**Comment by nomiddlename** [comment]
Thanks @cula - I’m on vacation for the next week or so, but I’ll try to keep up with emails and things.

**Comment by cula** [comment]
Have a good holiday!
Because appenders are now independent from `log4js`, so maybe we should recode some to make it easier to communicate between appender and `log4js` and clearer about what to do if one appender want itself working with `log4js` correctly. The following are some thoughts:
1. There should be a way for appenders to feed back to `log4js` such as when there is some error coming up in the process of configuration/generating appenders. Such as just return `undefined` when call the `configure` method of the appender or just throw an Error. 
2. One appender should clearer be a class (es6) with method `log` and `shutdown` instead of a function as now. It will be newed and returned in the `configure` method. It's a little strange that now appender is a function with shutdown method.

**Comment by cula** [comment]
I found the mutlFile appender depends on the file appender. So it cannot be done before the file appender finished splitting out. Or I will need to move all file appender code here. This sounds like a little dirty.

**Comment by cula** [comment]
@nomiddlename Hope u had a good holiday! Please take a look at these comments.

**Comment by nomiddlename** [comment]
I wonder if it would be better to keep the multiFile appender in the core then, with the other file appenders? The other option would be to move all the file appenders out into a single repo, maybe.

**Comment by cula** [comment]
I found fileAppender, fileSyncAppender, multiFileAppender, dateFileAppender in the v2.x. After I recoded the rollingstream, fileAppender can do what is done in dateFileAppender.  I think fileSyncAppender is no longer needed. How about creating one fileAppender repo to provide the features of fileAppender, multiFileAppender, and dateFileAppender?

**Comment by nomiddlename** [comment]
I'm going to close this one. We'll keep the file-based appenders in the core for now, but it does sound like we can merge them in the future.
