### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by rightaway** [log4js-node/log4js-node#608]
`ISO8601` format is `2017-05-01 20:18:44.729` and `ISO8601_WITH_TZ_OFFSET` format is `2017-05-01T20:18:44.729+0200`. For readability the latter it should be `2017-05-01 20:18:44.729 +0200` (with spaces in between the parts to be consistent with `ISO8601` format).

**Comment by ramicohen303** [comment]
The date formats are handled by a library called [date-format](https://github.com/nomiddlename/date-format). Please suggest this issue there.

On a side note, I think the right solution is to replace the space in ISO8601 with a T, since that is the standard ISO8601 format. I understand the readability part, and maybe the date-format can add types like ISO8601_READABLE, but standard ISO8601 formats have no spaces.

**Comment by nomiddlename** [comment]
Closing this one  - I've created an issue in date-format for it: https://github.com/nomiddlename/date-format/issues/8
