### ISSUE TITLE
How to use this in an electron + react app?

### ISSUE THREAD

**Issue by drdgvhbh** [log4js-node/log4js-node#623]
Everytime i try including `const log4js = require('log4js');` i just get the following error.

`path.js:7 Uncaught TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at Configuration.loadAppenderModule (http://localhost:1212/dist/renderer.dev.js:17882:38)
    at Configuration.createAppender (http://localhost:1212/dist/renderer.dev.js:17887:33)
    at appenderNames.forEach (http://localhost:1212/dist/renderer.dev.js:17930:47)
    at Array.forEach (native)
    at Configuration.set appenders [as appenders] (http://localhost:1212/dist/renderer.dev.js:17923:19)
    at new Configuration (http://localhost:1212/dist/renderer.dev.js:18028:20)
    at configure (http://localhost:1212/dist/renderer.dev.js:18998:12)
    at Object../node_modules/log4js/lib/log4js.js (http://localhost:1212/dist/renderer.dev.js:19085:1)`

The boilerplate im using is [this](https://github.com/chentsulin/electron-react-boilerplate).

**Comment by nomiddlename** [comment]
Ah, ok - I think I get what's happening. The electron/react stuff is using webpack under the hood, and webpack doesn't pick up the dynamic requires that log4js is doing. The workaround for this would be to require the initial appender that log4js needs manually. You can either do this by adding `require('./node_modules/log4js/lib/appenders/stdout')` to your file before you require log4js the first time, or adding it to the webpack config somewhere to pre-load it. If this is running in a browser you're probably going to want to configure log4js to use the console appender instead of stdout as well. Your code would look something like this:
```
require('./node_modules/log4js/lib/appenders/stdout');
require('./node_modules/log4js/lib/appenders/console');
const log4js = require('log4js');
log4js.configure({
  appenders: { out : { type: 'console' } },
  categories: { default: { appenders: ['out'], level: 'debug' } }
});
```

You may need to mess around with the paths I've used above - it'll depend on where your node modules is relative to the calling code.

**Comment by nomiddlename** [comment]
I hope my workaround above helped you. I'm going to close this issue, but please reopen it if you need more help.

**Comment by searene** [comment]
Hi @nomiddlename,

I've already added the `require` code as demonstrated by you, but I'm still getting the error.

```javascript
WARNING in ./~/log4js/lib/configuration.js
52:13-32 Critical dependency: the request of a dependency is an expression
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Configuration.loadAppenderModule (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:1921:38)
    at Configuration.createAppender (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:1926:33)
    at appenderNames.forEach (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:1969:47)
    at Array.forEach (native)
    at Configuration.set appenders [as appenders] (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:1962:19)
    at new Configuration (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:2067:20)
    at Object.configure (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:1061:12)
    at Object.<anonymous> (/home/searene/WebstormProjects/webpack-test/dist/bundle.js:4050:8)
```

This is a simple webpack project, it just bundles everything inside `index.js` into a big `bundle.js` file.

**index.js**

```javascript
require('../node_modules/log4js/lib/appenders/stdout');
require('../node_modules/log4js/lib/appenders/console');
const log4js = require('log4js');
log4js.configure({
  appenders: { out : { type: 'console' } },
  categories: { default: { appenders: ['out'], level: 'debug' } }
});
```

**webpack.config.js**

```javascript
module.exports = webpackConfig = {
  entry: './src/index.js',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js'
  },
  target: 'node'
};
```

Since the problem hasn't been solved, could you reopen this issue?

**Comment by nomiddlename** [comment]
In your `log4js.configure`, could you try to replace `type: 'console'` with `type: '../node_modules/log4js/lib/appenders/console'`. The path error you're seeing is because it's trying to require console from the current directory.

**Comment by searene** [comment]
Hi,

Thanks for you reply, but it still didn't work.

I dug into the source code for a little bit, and found that in the following code in `configuration.js`

```js
  tryLoading(modulePath) {
      ...
      return require(modulePath); //eslint-disable-line
      ...
  }
```

The line `return require(modulePath);` was always replaced by webpack with the following one.

```js
return !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()); //eslint-disable-line
```

So maybe webpack doesn't allow dynamic require at all? If this is the case, we have to modify log4js' source code to make it work with webpack.

**Comment by nomiddlename** [comment]
You could be right about webpack not allowing dynamic requires at all. @tmihalcin was looking at this, trying to get it working - any help for @searene?

**Comment by tmihalcin** [comment]
@searene since the requires are dynamic, webpack doesn't know which appenders will be needed and doesn't pack any at all.
I got it working using this workaround:
```
const stdout = require('log4js/lib/appenders/stdout');
import * as Configuration from 'log4js/lib/configuration';

Configuration.prototype.loadAppenderModule = function(_type: string): void {
	return stdout;
};
```

**Comment by shadower01** [comment]
@tmihalcin thanks, that workaround worked for me (at least with the console appender.. I'll try the file appender).
------------ recommendation to improve the library=>
In my case, I'm not using cluster and despite I set `disableClustering: true`, I got an error because in log4js.js version 1.0 line 214 you ask `if (cluster) { cluster.removeListener('message', receiver);}` I modified log4js.js line 214 to `if (cluster && cluster.removeListener)` but I think it is better to ask `if !disableClustering`.

**Comment by nomiddlename** [comment]
Closing this issue. There have been some changes in version 3.x of log4js to support webpack a bit better. (You still won't be able to log to a file from the browser though, but the console appender should work). Please re-open if you're still having problems.
