### ISSUE TITLE
Is there a rabbitMQ appender? I saw the redis appender MR, I need to send the log to rabbitMQ, or do I need to add an appender myself?

### ISSUE THREAD

**Issue by Anteoy** [log4js-node/log4js-node#642]
Is there a rabbitMQ appender? I saw the redis appender MR, I need to send the log to rabbitMQ, or do I need to add an appender myself?

**Comment by nomiddlename** [comment]
There isn't a rabbitmq appender in the core. I'd be happy to see a pull request that implements it. 

I notice you've pushed `log4js-rabbit` to NPM. It's very confusing for users because you've not updated the package.json to distinguish your fork from the main one (the readme, the source and issues links, etc). If you're intending to use your fork to create a pull request for adding a rabbit mq appender to the core, then please delete the `log4js-rabbit` from NPM. If you're intending to publish a rabbit mq appender as a plugin for log4js, then you should update the NPM details to reflect that and remove all the unnecessary code from your repo (otherwise users will be downloading a whole load of extra files and dependencies that they won't need).

**Comment by Anteoy** [comment]
I'll be pleased to submit a PR for this purpose, which is now added to my repository. I'll reorganize the code, add the test, and then submit. I'll delete the existing log4js-rabbit from the npm repository.
