### ISSUE TITLE
2.x太臃肿了

### ISSUE THREAD

**Issue by ugrg** [log4js-node/log4js-node#659]
2.x整个log4js的关联引用太大了,是不是考虑做成插件而不是直接作为依赖装载进来.

**Comment by nomiddlename** [comment]
According to Google translate, this is Chinese - which I don't speak, sorry. So forgive me if I haven't understood the problem, but it looks like you're complaining about log4js including a lot of dependencies that you're not using (the optional dependencies for the appenders). This should be fixed in version 3.x, as we will be moving the appenders into their own projects.

**Comment by ugrg** [comment]
哈哈,对于英文,我也是仅能阅读,写不了, 所以说,"google翻译是个好东西."

期待你的3.x
