### ISSUE TITLE
Logging with GELF appender produces TS-Errors

### ISSUE THREAD

**Issue by SockeThe2nd** [log4js-node/log4js-node#664]
I am using log4js in a typescript project and wanted to add the GELF-appender as documented [here](https://log4js-node.github.io/log4js-node/gelf.html). Logging as documented produces a ts-error as the first argument expected is the message as a string and not the gelf-data which is an object.

I fixed this by adding a .d.ts-file with the following declaration:
```typescript
import * as log4js from "log4js";

declare module 'log4js' {
    interface Logger {
        trace(gelfData: GELF, message: string, ...args: any[]): void;
        debug(gelfData: GELF, message: string, ...args: any[]): void;
        info(gelfData: GELF, message: string, ...args: any[]): void;
        warn(gelfData: GELF, message: string, ...args: any[]): void;
        error(gelfData: GELF, message: string, ...args: any[]): void;
        fatal(gelfData: GELF, message: string, ...args: any[]): void;
    }
}

export interface GELF {
    GELF: Boolean,
    [key: string]: any
}
```

Perhaps the declarations of the logging-functions with GELF should directly be part of the types of log4js just like the gelf-appender itself.

**Comment by nomiddlename** [comment]
Hi @SockeThe2nd - would you be willing to be a test subject for me, please? I've just moved the GELF appender into its own module, in preparation for removing it from the core in version 3 of log4js. I've implemented the changes above in the [new module](https://github.com/log4js-node/gelf), but I'm not sure if there will be conflicts in the typescript definitions if you use the new module with the existing one.

To use the new module `npm install @log4js-node/gelf`, then change the type of your appender to `@log4js-node/gelf` instead of just `gelf`.

**Comment by nomiddlename** [comment]
Closing due to lack of follow-up information. If still an issue, please raise against the [gelf appender repo](https://github.com/log4js-node/gelf).
