### ISSUE TITLE
Interface doesn't exist for setting the global log level

### ISSUE THREAD

**Issue by harish-valuelabs** [log4js-node/log4js-node#665]
For say I want to set the global log level , for instance log4js.setLevel('ERROR'). Such interface doesn't exists in given library.

**Comment by nomiddlename** [comment]
No, there isn't. This is intentional because to do this would require log4js to retain a reference to all loggers which caused problems in previous versions. It would also not work across processes in a clustered environment, which would cause confusion. However, within a process, you can set a level for all loggers with the same category like this:
```
const logger = log4js.getLogger('thing');
const otherLogger = log4js.getLogger('thing');
console.log(otherLogger.level); // outputs 'DEBUG'
logger.level = 'ERROR';
console.log(otherLogger.level); // outputs 'ERROR'
```
