### ISSUE TITLE
TCP server produces duplicate log messages

### ISSUE THREAD

**Issue by florianreinhart** [log4js-node/log4js-node#761]
`dataSoFar` in [tcp-server.js](https://github.com/log4js-node/log4js-node/blob/v3.0.1/lib/appenders/tcp-server.js) is not reset to an empty string when events are processed.

I'll create a PR to fix this issue.

**Comment by nomiddlename** [comment]
Thanks for fixing this. There's probably a few more changes I need to make in order to make this more robust - like handling what to do in the client when the server is unavailable. I was thinking of adding a circular buffer, and dropping any old log messages to console.error so that the client doesn't run out of memory waiting for the server to come back. If you've got any suggestions for improvements, then please raise them. Even better, if you feel like writing them 😄 

Your fix has been published to npm in version 3.0.2, thanks again.
