### ISSUE TITLE
Add the ability to supply an appender instance in configuration

### ISSUE THREAD

**Issue by kaxelson** [log4js-node/log4js-node#832]
Hey all.  I was thinking about adding an option to provide an appender instance in the configuration, rather than just a string meant to be the target of a require statement.  The idea would be to provide the appender object under appenders.<name>.type.  Then I would check to see if appender.<name>.type has a configure property.  If so, treat it as an appender instance and skip the load step.  Changes would go in appenders/index.js near the beginning of the createAppender function.  Any thoughts on this?

**Comment by nomiddlename** [comment]
Sorry for not getting back to you sooner - thanks for the pull request.  Just to clear up some terminology - this change allows you to include an appender module directly in the config, instead of having it required. An appender instance is what is returned from calling `configure` in the appender module. 

When would you use this, and not just put your appender module code in a separate module anyway? I can see the benefit of being able to include an appender instance in the config (configure it separately, plus you get more control over the lifecycle), but not the appender module.

**Comment by kaxelson** [comment]
My apologies now for not getting back to you sooner.

Your point about the terminology is understood.

This could be used in situations where you'd like to inline a simple appender implementation.  No need to break it into a separate package.  Simply provide an object with a configure function.

You still have control since you can make the object you provide (and its configure function) do anything you want.

It also fits nicely into the existing code with the only change needed being to bypass the appender module lookup.

Finally, it simplifies working with pnpm and webpack which have difficulties dealing with the current appender module lookup logic.  pnpm has an issue because of the directory structure it creates.  It is unable to find the module without a custom pnpmfile.js.  webpack has an issue because of the fact that what is being required is not know before runtime.

**Comment by troppoli** [comment]
I'd sure like this.

We use typescript and webpac. So to get this working they way it is now, I need to create a new entrypoint for the appender in the webpack config so that a file can be generated so you can require it. Since we're building to a stage dir and running electron I have to massage the path for the require at runtime based on if we're running out of the debugger.

Just handing the configure function would be much easier, especially since this is a tool that we're just using for the in-house beta cycle.

**Comment by nomiddlename** [comment]
Release @kaxelson's change to NPM in version 4.4.0
