### ISSUE TITLE
MaxListenersExceededWarning when adding loggers dynamically

### ISSUE THREAD

**Issue by andymel123** [log4js-node/log4js-node#886]
Hi, 

I append loggers dynamically with the solution posted [here](https://github.com/log4js-node/log4js-node/issues/437#issuecomment-314587107).

The problem with that. With each added logger, file.js adds a 'SIGHUP' listener to process.
`process.on('SIGHUP', app.sighupHandler);`

Is there a way to tell log4js when I am finished with the specific logger? So that it can remove the listener again? The shutdown function on log4js would shutdown all appenders I guess.

My current workaround (typescript) just removes the listener after it's added. But that's just fighting a symptom of a bigger problem.
`    process.addListener("newListener", (type, listener) => {...removing that listener again...}`

log4js version "^4.3.0"

**Comment by nomiddlename** [comment]
I commented on the other issue #437, but I'll comment here as well in case other people are searching for the same thing. You can use the timeout parameter of the [multiFile appender](https://log4js-node.github.io/log4js-node/multiFile.html) to close the underlying file appenders when they have not been used for a while. That may fix your problem. 

The real issue is that each file appender adds its own SIGHUP handler when they could all use the same one. See also #852

**Comment by peteriman** [comment]
This has been patched and should be closed together with #852 once the PR #1110 is approved.
