### ISSUE TITLE
timezoneOffset can't work

### ISSUE THREAD

**Issue by pscj** [log4js-node/log4js-node#895]
I found the code was removed from layout.js.  It can't work anymore. What's happend?

**Comment by nomiddlename** [comment]
Yes, I removed it because it was making things complicated (and in a couple of situations did not actually work either). Layouts now only output time as either local time (set by the timezone of the machine it is running on), or as UTC if you specify that format. If you want to do something different then you can create a custom layout, or create a custom token for the pattern layout.

**Comment by nomiddlename** [comment]
Closing this issue, please re-open if you think there is a bug.
