### ISSUE TITLE
Propose an Appender for logfmt

### ISSUE THREAD

**Issue by xinbenlv** [log4js-node/log4js-node#927]
Hi log4js-node community

With the increasing popularity, it make sense to have a logfmt appender based on Heroku's canonical log format structure, the [logfmt](https://brandur.org/logfmt), as indicated in [](https://blog.heroku.com/hutils-explore-your-structured-data-logs). 

I can contribute to create one. but before that, my question is, should it exist in log4js-node just like other "additional appenders" or should it be just under my own git repository? I can create one but likely not able to keep maintaining for long so ideally I am happy to donate it to log4js-node community.

Thank you!

Related to [commit:ebcb014](https://github.com/google/wikiloop-battlefield/commit/ebcb0141da25a697a49601ce21464131d6e057a0) under https://github.com/google/wikiloop-battlefield/issues/66

**Comment by nomiddlename** [comment]
This sounds like a layout rather than an appender to me, if I've understood the concept correctly. You'd use the logfmt layout with a file appender, for instance. If it is just a layout, and the code is not too large, then I'd be happy to include it in log4js core. A full appender would be better as a separate repo/project though - that way it is an optional download for anyone that needs it.

**Comment by nomiddlename** [comment]
Closing this one, as there is no issue to fix. Good luck if you decide to write your layout or appender.
